/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/error/404.vue')['default']
    AboutCard: typeof import('./src/components/settings/AboutCard.vue')['default']
    AlternativeCodeDialog: typeof import('./src/components/auth/AlternativeCodeDialog.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AttendanceManagementDialog: typeof import('./src/components/attendance/AttendanceManagementDialog.vue')['default']
    AttendanceSidebar: typeof import('./src/components/attendance/AttendanceSidebar.vue')['default']
    CacheManager: typeof import('./src/components/CacheManager.vue')['default']
    ChatWidget: typeof import('./src/components/ChatWidget.vue')['default']
    CloudMigrationDialog: typeof import('./src/components/settings/CloudMigrationDialog.vue')['default']
    CloudNamespaceInfoCard: typeof import('./src/components/settings/cards/CloudNamespaceInfoCard.vue')['default']
    ConciseExamCard: typeof import('./src/components/home/ConciseExamCard.vue')['default']
    DataProviderSettingsCard: typeof import('./src/components/settings/cards/DataProviderSettingsCard.vue')['default']
    DeviceAuthDialog: typeof import('./src/components/auth/DeviceAuthDialog.vue')['default']
    DisplaySettingsCard: typeof import('./src/components/settings/cards/DisplaySettingsCard.vue')['default']
    EchoChamberCard: typeof import('./src/components/settings/cards/EchoChamberCard.vue')['default']
    EditSettingsCard: typeof import('./src/components/settings/cards/EditSettingsCard.vue')['default']
    EventSender: typeof import('./src/components/EventSender.vue')['default']
    ExamConfigEditor: typeof import('./src/components/ExamConfigEditor.vue')['default']
    ExamScheduleCard: typeof import('./src/components/home/ExamScheduleCard.vue')['default']
    FirstTimeGuide: typeof import('./src/components/auth/FirstTimeGuide.vue')['default']
    FloatingICP: typeof import('./src/components/FloatingICP.vue')['default']
    FloatingToolbar: typeof import('./src/components/FloatingToolbar.vue')['default']
    GlobalMessage: typeof import('./src/components/GlobalMessage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HitokotoCard: typeof import('./src/components/HitokotoCard.vue')['default']
    HitokotoSettings: typeof import('./src/components/HitokotoSettings.vue')['default']
    HomeActions: typeof import('./src/components/home/HomeActions.vue')['default']
    HomeworkEditDialog: typeof import('./src/components/HomeworkEditDialog.vue')['default']
    HomeworkGrid: typeof import('./src/components/home/HomeworkGrid.vue')['default']
    HomeworkTemplateCard: typeof import('./src/components/settings/cards/HomeworkTemplateCard.vue')['default']
    InitServiceChooser: typeof import('./src/components/InitServiceChooser.vue')['default']
    KvDatabaseCard: typeof import('./src/components/settings/cards/KvDatabaseCard.vue')['default']
    KvInitialize: typeof import('./src/components/KvInitialize.vue')['default']
    MessageLog: typeof import('./src/components/MessageLog.vue')['default']
    ProgressiveRegisterPage: typeof import('./src/components/auth/ProgressiveRegisterPage.vue')['default']
    RandomPicker: typeof import('./src/components/RandomPicker.vue')['default']
    RandomPickerCard: typeof import('./src/components/settings/cards/RandomPickerCard.vue')['default']
    RateLimitModal: typeof import('./src/components/RateLimitModal.vue')['default']
    ReadOnlyTokenWarning: typeof import('./src/components/ReadOnlyTokenWarning.vue')['default']
    RefreshSettingsCard: typeof import('./src/components/settings/cards/RefreshSettingsCard.vue')['default']
    RelativeTimeDisplay: typeof import('./src/components/RelativeTimeDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerSettingsCard: typeof import('./src/components/settings/cards/ServerSettingsCard.vue')['default']
    SettingGroup: typeof import('./src/components/settings/SettingGroup.vue')['default']
    SettingItem: typeof import('./src/components/settings/SettingItem.vue')['default']
    SettingsCard: typeof import('./src/components/SettingsCard.vue')['default']
    SettingsExplorer: typeof import('./src/components/settings/SettingsExplorer.vue')['default']
    SettingsLinkGenerator: typeof import('./src/components/SettingsLinkGenerator.vue')['default']
    StudentListCard: typeof import('./src/components/settings/StudentListCard.vue')['default']
    StudentNameManager: typeof import('./src/components/StudentNameManager.vue')['default']
    SubjectManagementCard: typeof import('./src/components/settings/cards/SubjectManagementCard.vue')['default']
    ThemeSettingsCard: typeof import('./src/components/settings/cards/ThemeSettingsCard.vue')['default']
    TokenInputDialog: typeof import('./src/components/auth/TokenInputDialog.vue')['default']
    UnsavedWarning: typeof import('./src/components/common/UnsavedWarning.vue')['default']
    UrgentNotification: typeof import('./src/components/UrgentNotification.vue')['default']
    UrgentTestDialog: typeof import('./src/components/UrgentTestDialog.vue')['default']
  }
}
