/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authorize': RouteRecordInfo<
      '/authorize',
      '/authorize',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/CacheManagement': RouteRecordInfo<
      '/CacheManagement',
      '/CacheManagement',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cses2wakeup': RouteRecordInfo<
      '/cses2wakeup',
      '/cses2wakeup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug': RouteRecordInfo<
      '/debug',
      '/debug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug-init': RouteRecordInfo<
      '/debug-init',
      '/debug-init',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug-socket': RouteRecordInfo<
      '/debug-socket',
      '/debug-socket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/exam-editor/[id]': RouteRecordInfo<
      '/exam-editor/[id]',
      '/exam-editor/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/exam-player': RouteRecordInfo<
      '/exam-player',
      '/exam-player',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examschedule': RouteRecordInfo<
      '/examschedule',
      '/examschedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/list/': RouteRecordInfo<
      '/list/',
      '/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/list/[id]': RouteRecordInfo<
      '/list/[id]',
      '/list/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/socket-debugger': RouteRecordInfo<
      '/socket-debugger',
      '/socket-debugger',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/404.vue': {
      routes:
        | '/404'
      views:
        | never
    }
    'src/pages/authorize.vue': {
      routes:
        | '/authorize'
      views:
        | never
    }
    'src/pages/CacheManagement.vue': {
      routes:
        | '/CacheManagement'
      views:
        | never
    }
    'src/pages/cses2wakeup.vue': {
      routes:
        | '/cses2wakeup'
      views:
        | never
    }
    'src/pages/debug.vue': {
      routes:
        | '/debug'
      views:
        | never
    }
    'src/pages/debug-init.vue': {
      routes:
        | '/debug-init'
      views:
        | never
    }
    'src/pages/debug-socket.vue': {
      routes:
        | '/debug-socket'
      views:
        | never
    }
    'src/pages/exam-editor/[id].vue': {
      routes:
        | '/exam-editor/[id]'
      views:
        | never
    }
    'src/pages/exam-player.vue': {
      routes:
        | '/exam-player'
      views:
        | never
    }
    'src/pages/examschedule.vue': {
      routes:
        | '/examschedule'
      views:
        | never
    }
    'src/pages/list/index.vue': {
      routes:
        | '/list/'
      views:
        | never
    }
    'src/pages/list/[id].vue': {
      routes:
        | '/list/[id]'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/socket-debugger.vue': {
      routes:
        | '/socket-debugger'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
